version: '3'

services:
#  pgsql:
#    container_name: pgsql
#    image: postgres:${POSTGRES_VERSION}-alpine
#    restart: always
#    environment:
#      POSTGRES_DB: $POSTGRES_DB
#      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
#      POSTGRES_USER: $POSTGRES_USER
#      TZ: Europe/Moscow
#      PGTZ: Europe/Moscow
#    ports:
#      - "55352:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw

  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    ports:
      - '9000:9000'
#    depends_on:
#      - pgsql
    volumes:
      - ./app:/var/www/symfony-user-app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/symfony-user-app:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
#      - pgsql
    ports:
      - "80:80"

volumes:
  db-data:
    driver: local