version: '3'

services:
#  pgsql:
#    container_name: pgsql
#    image: postgres:${POSTGRES_VERSION}-alpine
#    restart: always
#    environment:
#      POSTGRES_DB: $POSTGRES_DB
#      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
#      POSTGRES_USER: $POSTGRES_USER
#      TZ: Europe/Moscow
#      PGTZ: Europe/Moscow
#    ports:
#      - "55352:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw

  php-fpm: &php
    container_name: php-fpm
    restart: always
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
    ports:
      - '9000:9000'
#    depends_on:
#      - pgsql
    volumes:
      - ./app:/var/www/symfony-user-app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/symfony-user-app:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
#      - pgsql
    ports:
      - "80:80"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.11-management-alpine
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    container_name: mailhog
    restart: always
    image: mailhog/mailhog:v1.0.1
    expose:
      - "1025"
      - "8025"
    ports:
      - "127.0.0.1:1025:8025"

  worker-notification:
    container_name: worker-notification
    <<: *php
    user: ${UID}:${GUID}
    command: php /var/www/symfony-user-app/bin/console messenger:consume --time-limit=3600 async --queues=notification_queue
    ports:
      - "9005:9005"

volumes:
  db-data:
    driver: local
  rabbitmq-data: